Flytt rekvisisjonPersonundersoekelse til under politi-mappe
domstolene/ESAS pull request #124
Opened 2023-10-25 14:06 UTC by AStrand94

Bør ligge under politi da det er politiet som sender denne til kriminalomsorgen

2023-10-26 07:08 UTC, runemelhus approved these changes

2023-10-26 11:53 UTC, oyvindbjorlow requested changes
Hei! Vi i KO ønsker eie denne siden vi eier definisjonen av nødvendig informasjon for å starte arbeidet med en personundersøkelse. Det er også slik at både domstol og politi kan rekvirere PeU. Det virker ikke rett at politiet skal definere behovet som en av to mulige avsendere.

2023-11-07 14:12 UTC, calle-777 commented
> Hei! Vi i KO ønsker eie denne siden vi eier definisjonen av nødvendig informasjon for å starte arbeidet med en personundersøkelse. Det er også slik at både domstol og politi kan rekvirere PeU. Det virker ikke rett at politiet skal definere behovet som en av to mulige avsendere.

Var det ikke sånn at vi var enige om at PU undersøkelse alltid skulle gå via politiet (altså aldri direkte fra domstolen)?

2023-11-08 16:06 UTC, oyvindbjorlow commented
> > Hei! Vi i KO ønsker eie denne siden vi eier definisjonen av nødvendig informasjon for å starte arbeidet med en personundersøkelse. Det er også slik at både domstol og politi kan rekvirere PeU. Det virker ikke rett at politiet skal definere behovet som en av to mulige avsendere.
> 
> Var det ikke sånn at vi var enige om at PU undersøkelse alltid skulle gå via politiet (altså aldri direkte fra domstolen)?

Stemmer at domstolene ikke har prioritert lage funskjonalitet for å rekvirere selv i denne omgang. Men vi ønsker fortsatt eie denne modellen. Antar det er parallelt til at politiet antagelig selv vil eie hva som er "nok" for å motta en anmeldelse (fra ulike anmeldere). 

Ellers: Skjønte på Martin at arkitektene lurte på å flytte kontraktene under en "fagområde"-struktur i stedet for "etat". Type legge alle VT-meldinger under "./varetekt". Det høres lurt ut, da unngår vi at man infererer eierskap ut fra plassering i strukturen.

2023-11-09 08:13 UTC, calle-777 commented
> > > Hei! Vi i KO ønsker eie denne siden vi eier definisjonen av nødvendig informasjon for å starte arbeidet med en personundersøkelse. Det er også slik at både domstol og politi kan rekvirere PeU. Det virker ikke rett at politiet skal definere behovet som en av to mulige avsendere.
> > 
> > 
> > Var det ikke sånn at vi var enige om at PU undersøkelse alltid skulle gå via politiet (altså aldri direkte fra domstolen)?
> 
> Stemmer at domstolene ikke har prioritert lage funskjonalitet for å rekvirere selv i denne omgang. Men vi ønsker fortsatt eie denne modellen. Antar det er parallelt til at politiet antagelig selv vil eie hva som er "nok" for å motta en anmeldelse (fra ulike anmeldere).
> 
> Ellers: Skjønte på Martin at arkitektene lurte på å flytte kontraktene under en "fagområde"-struktur i stedet for "etat". Type legge alle VT-meldinger under "./varetekt". Det høres lurt ut, da unngår vi at man infererer eierskap ut fra plassering i strukturen.

Jeg skal ikke legge meg borti hvem som skal "eie" denne. Men ser gode argumenter for at akkurat denne kanskje bør ligge hos KDI selv om prinsippet er at avsender skal "eie" på generelt grunnlag. Bli enig med politiet..!
Ellers støtter vi på DA det å omlegge strukturen slik at oppdelingen blir på "fagområdet" i stedet for "etat".

2023-11-09 11:55 UTC, JosteinKlakegg commented
> fagområde

Støtter å legge opp til fagområde. 

Se gjerne her for eksempel på lignende repository hvor det er veldig mange aktører i form av avsendere og konsumenter av meldingene og enda mer fokus på å bygge en "bransjestandard", kontra 1-1 meldinger mellom aktører.  
https://git.sarepta.test.ehelse.no/publisert/standarder/-/tree/master/skjema

2023-11-21 12:50 UTC, AStrand94 commented
Erstattes av #131

2023-11-21 12:50 UTC, closed without merging